### ISSUE TITLE
Upload file gambar / video via widget flutter

### ISSUE THREAD

**Issue by barokurniawan** [qiscus/qiscus-multichannel-widget-flutter#1]
Di example ini cuma ada contoh untuk send text message aja ya?
untuk upload file nya gimana ya?

Terimakasih

**Comment by apiep** [comment]
untuk upload attachment gambar maupun file, sudah di implementasi di commit ini ya https://github.com/qiscus/qiscus-multichannel-widget-flutter/commit/44e1c4087859d9e6f0a927a80ecd54078381d0bf

**Comment by barokurniawan** [comment]
mantap mas @apiep , Terimakasih.
