### ISSUE TITLE
Tidak bisa menerima balasan dari Agent secara realtime

### ISSUE THREAD

**Issue by barokurniawan** [qiscus/qiscus-multichannel-widget-flutter#2]
Hallo team qiscus,
saya test dan jalankan example widget ini kok nggak dapet message balasan dari admin/agent secara realtime ya?
harus reload dulu halaman, baru pesan dari admin/agent masuk.

Terimakasih.

**Comment by hadievm** [comment]
tested 1.0.0-beta.3,
but still cannot get realtime message from agent.

**Comment by apiep** [comment]
can try again in the latest version (1.0.0-beta.4), as there is an update for qiscus chat sdk which fix the realtime issue
